-- TABLE CREATION
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200),
    ADDRESS VARCHAR2(255),
    PHONE NUMBER(20) UNIQUE,
    EMAIL VARCHAR2(200) UNIQUE
);

CREATE TABLE ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) CHECK (ACCOUNT_TYPE IN ('SAVINGS','CURRENT')),
    BALANCE NUMBER(12,2) DEFAULT 0,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('ACTIVE','INACTIVE')),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    TRANSACTION_TYPE VARCHAR2(20) CHECK (TRANSACTION_TYPE IN ('DEPOSIT','WITHDRAW')),
    AMOUNT NUMBER(12,2) NOT NULL,
    TRANSACTION_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
);

CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE,
    PASSWORD VARCHAR2(20) NOT NULL,
    ROLE VARCHAR2(20) CHECK (ROLE IN ('ADMIN','CLERK','MANAGER'))
);

CREATE TABLE LOANS (
    LOAN_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    LOAN_TYPE VARCHAR2(30),
    AMOUNT NUMBER(12,2),
    INTEREST_RATE NUMBER(5,2),
    START_DATE DATE,
    END_DATE DATE,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Active','Closed')),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE LOAN_PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    LOAN_ID NUMBER NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    AMOUNT_PAID NUMBER(12,2),
    FOREIGN KEY (LOAN_ID) REFERENCES LOANS(LOAN_ID)
);

CREATE TABLE BRANCHES (
    BRANCH_ID NUMBER PRIMARY KEY,
    BRANCH_NAME VARCHAR2(100),
    ADDRESS VARCHAR2(255),
    PHONE VARCHAR2(15)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    DESIGNATION VARCHAR2(50),
    SALARY NUMBER(10,2),
    BRANCH_ID NUMBER,
    FOREIGN KEY (BRANCH_ID) REFERENCES BRANCHES(BRANCH_ID)
);

CREATE TABLE CARDS (
    CARD_ID NUMBER PRIMARY KEY,
    ACCOUNT_ID NUMBER NOT NULL,
    CARD_NUMBER VARCHAR2(20) UNIQUE,
    CARD_TYPE VARCHAR2(20) CHECK (CARD_TYPE IN ('Debit','Credit')),
    ISSUE_DATE DATE,
    EXPIRY_DATE DATE,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('Active','Blocked')),
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID)
);


